export const META_SDK_OPTIONS = Symbol('META_SDK_OPTIONS');
export const FACEBOOK_OAUTH_OPTIONS = Symbol('FACEBOOK_OAUTH_OPTIONS');
export const INSTAGRAM_OAUTH_OPTIONS = Symbol('INSTAGRAM_OAUTH_OPTIONS');
export const META_WEBHOOK_OPTIONS = Symbol('META_WEBHOOK_OPTIONS');
export const META_SDK_LOGGER = Symbol('META_SDK_LOGGER');
export const META_SDK_RESOLVED_CONFIG = Symbol('META_SDK_RESOLVED_CONFIG');
